-- schema.sql
-- Esquema completo de la base de datos de la Herramienta Escazú
-- Generado a partir de los INSERTs de neondb_export_*.sql
-- Uso recomendado:
--   1) Ejecutar este archivo para crear las tablas vacías
--   2) Ejecutar neondb_export_YYYYMMDD_HHMM.sql para poblar los datos

-- =============================
-- Limpieza previa (opcional)
-- =============================
DROP TABLE IF EXISTS "responses"       CASCADE;
DROP TABLE IF EXISTS "assessments"     CASCADE;
DROP TABLE IF EXISTS "questions"       CASCADE;
DROP TABLE IF EXISTS "modules"         CASCADE;
DROP TABLE IF EXISTS "response_options" CASCADE;
DROP TABLE IF EXISTS "users"           CASCADE;
DROP TABLE IF EXISTS "admins"          CASCADE;

-- =============================
-- Tabla: admins
-- =============================
CREATE TABLE "admins" (
  "id"            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username"      TEXT    NOT NULL UNIQUE,
  "password_hash" TEXT    NOT NULL,
  "created_at"    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================
-- Tabla: users
-- =============================
CREATE TABLE "users" (
  "id"           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"         TEXT        NOT NULL,
  "contact"      TEXT        NOT NULL,
  "entity"       TEXT        NOT NULL,
  "municipality" TEXT        NOT NULL,
  "created_at"   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================
-- Tabla: modules
-- =============================
CREATE TABLE "modules" (
  "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name"        TEXT NOT NULL,
  "description" TEXT,
  "order_index" INTEGER NOT NULL
);

-- =============================
-- Tabla: questions
-- =============================
CREATE TABLE "questions" (
  "id"              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "module_id"       INTEGER NOT NULL,
  "question_text"   TEXT    NOT NULL,
  "question_type"   TEXT,
  "order_index"     INTEGER NOT NULL,
  "recommendations" TEXT
);

-- =============================
-- Tabla: response_options
-- =============================
CREATE TABLE "response_options" (
  "id"                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "option_text"                TEXT    NOT NULL,
  "points"                     INTEGER NOT NULL,
  "excludes_from_calculation"  BOOLEAN NOT NULL DEFAULT FALSE
);

-- =============================
-- Tabla: assessments
-- =============================
CREATE TABLE "assessments" (
  "id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"           INTEGER NOT NULL,
  "total_score"       INTEGER NOT NULL,
  "max_possible_score" INTEGER NOT NULL,
  "percentage"        DOUBLE PRECISION NOT NULL,
  "classification"    TEXT    NOT NULL,
  "completed_at"      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "assessments_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE
);

-- =============================
-- Tabla: responses
-- =============================
CREATE TABLE "responses" (
  "id"                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id"           INTEGER NOT NULL,
  "question_id"       INTEGER NOT NULL,
  "response_option_id" INTEGER,
  "response_text"     TEXT,
  "created_at"        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT "responses_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE,
  CONSTRAINT "responses_question_id_fkey"
    FOREIGN KEY ("question_id") REFERENCES "questions"("id") ON DELETE CASCADE,
  CONSTRAINT "responses_response_option_id_fkey"
    FOREIGN KEY ("response_option_id") REFERENCES "response_options"("id")
);

-- =============================
-- Índices útiles (opcionales)
-- =============================
CREATE INDEX IF NOT EXISTS "idx_questions_module_id" ON "questions"("module_id");
CREATE INDEX IF NOT EXISTS "idx_responses_user_id"   ON "responses"("user_id");
CREATE INDEX IF NOT EXISTS "idx_responses_question_id" ON "responses"("question_id");
CREATE INDEX IF NOT EXISTS "idx_assessments_user_id" ON "assessments"("user_id");

-- Fin de schema.sql
